---
title: "final_notes"
author: "Zach White"
date: "December 5, 2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(R2jags)
library(dplyr)
library(MASS)
library(ggplot2)
library(car)
require(leaps)
library(BMA)
library(BAS)
# Online
#setwd("/home/grad/zmw5/Fall 2016/STA 721/STA_721/final_project")
# On machine
setwd("C:/Users/Zachary/Desktop/Fall 2016/STA 721/STA_721/final_project")
load("ames_train.Rdata")
load("ames_test.Rdata")
```

She mentions location, location, location
```{r}
lm.anova = lm(price~Neighborhood,data = ames_train)
summary(lm.anova)
anova(lm.anova)
#predict.lm(lm.anova,ames_test)

# Build Hierarchical Model with location
ames_train %>% group_by(Neighborhood) %>%
  summarise(min_price = min(price),q1 = quantile(price,.25),med.price = quantile(price,.5),mean.price = mean(price),q3 = quantile(price,.75), max.price = max(price))

# Levels of Neighborhood
levels.train = levels(ames_train$Neighborhood)
levels.test = levels(ames_test$Neighborhood)

levels.train == levels.test
```

I have an idea where we could use a hierarchical model with Neighborhood as the first level, and some of the more quantitative variables on the second.


First step. Get the data in a usable format
```{r}
# Practical subones
y = ames_train$price
indices = c(2,6,7,18,20,21,22,23,30,31,33,34,37,39,40,41,42,43,44,46,47,49,50:56,58,59,63,64,65,66,78,79)
X = ames_train[,indices]

X$Bldg.Type  = as.character(X$Bldg.Type)
X$Exter.Cond = as.character(X$Exter.Cond)
X$Exter.Qual = as.character(X$Exter.Qual)
X$Central.Air = as.character(X$Central.Air)
X$Bsmt.Cond = as.character(X$Bsmt.Cond)
X$Bsmt.Qual = as.character(X$Bsmt.Qual)
X$Heating = as.character(X$Heating)
X$Heating.QC = as.character(X$Heating.QC)
X$Kitchen.Qual = as.character(X$Kitchen.Qual)
X$Fireplace.Qu = as.character(X$Fireplace.Qu)
X$Garage.Qual = as.character(X$Garage.Qual)
X$Garage.Cond = as.character(X$Garage.Cond)

## This is the key
X[X == "Ex"] = 5
X[X == "Gd"] = 4
X[X == "TA"] = 3
X[X == "Fa"] = 2
X[X == "Po"] = 1
X$Heating[is.na(X$Heating)] = 0
X$Central.Air[is.na(X$Central.Air)] = 0
X[is.na(X)] = 0

X$Bldg.Type  = as.factor(X$Bldg.Type)
X$Exter.Cond = as.factor(X$Exter.Cond)
X$Exter.Qual = as.factor(X$Exter.Qual)
X$Bsmt.Cond = as.factor(X$Bsmt.Cond)
X$Bsmt.Qual = as.factor(X$Bsmt.Qual)
X$Central.Air = as.factor(X$Central.Air)
X$Heating = as.factor(X$Heating)
X$Heating.QC = as.factor(X$Heating.QC)
X$Kitchen.Qual = as.factor(X$Kitchen.Qual)
X$Fireplace.Qu = as.factor(X$Fireplace.Qu)
X$Garage.Qual = as.factor(X$Garage.Qual)
X$Garage.Cond = as.factor(X$Garage.Cond)

#BOX COX on y
modelling.data = as.data.frame(cbind(y,X))
initial.model = lm(y~.,data = modelling.data)
bc = boxcox(initial.model)
lambda = bc$x[which.max(bc$y)]
bc.mat = modelling.data %>% mutate(bc.y = (y^lambda-1) / lambda) %>% dplyr::select(-y)

#Area
log.area = log(bc.mat$area)
bc.mat$log.area = log.area
index.area = which(colnames(bc.mat) == "area")
bc.mat = bc.mat[,-index.area]
# X1st.Flr.SF
log.X1st.Flr.SF = log(bc.mat$X1st.Flr.SF)
bc.mat$log.X1st.Flr.SF = log.X1st.Flr.SF
index.X1st = which(colnames(bc.mat) == "X1st.Flr.SF")
bc.mat=bc.mat[,-index.X1st]
# X2nd.Flr.SF

# Total.Bsmt.SF

# Lot Area
log.lot.area = log(bc.mat$Lot.Area)
bc.mat$log.log.area = log.lot.area
index.lot = which(colnames(bc.mat) == "Lot.Area")
bc.mat = bc.mat[,-index.lot]

transformed.data = as.data.frame(bc.mat)
transform.model = lm(bc.y~.,data = transformed.data)
transform.mat = model.matrix(transform.model)

#Continuous pre-processing
cont.index = which(sapply(transformed.data,class) == "numeric")
integer.index = which(sapply(transformed.data,class) == "integer")
factor.index = which(sapply(transformed.data,class) == "factor")

scaled.mat = as.data.frame(scale(transformed.data[,cont.index]))
names.cont = names(scaled.mat)
for(i in 1:ncol(scaled.mat)){
  index = which(names(transformed.data) == names.cont[i])
  transformed.data[,index] = scaled.mat[,i]
}
# So the transformations.  I did a boxcox.  Did some logs.  Then I scaled the continuous ones?
y.index = which(names(transformed.data) == "bc.y")
y.fin = transformed.data[,y.index]
X.fin = transformed.data[,-y.index]
```

I now perform the most basic ones
```{r}

```